name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # Atualiza todo dia à meia-noite
  workflow_dispatch:       # Permite rodar manualmente
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: allan516
          outputs: dist/snake.svg
      - name: Push to Output Branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
